name: runescape
base: core20
title: RuneScape
version: git
summary: RuneScape, the free MMORPG by Jagex LTD
description: |
  Explore the fantasy world of Gielinor in the worlds most popular free to play MMORPG!
  This snap provides both Old School RuneScape and RuneScape 3!
type: app
grade: stable
confinement: strict
license: MIT
assumes: 
  - command-chain
architectures:
  - build-on: amd64
compression: lzo

parts:
  rs3-gpg:
    plugin: dump
    source: .
    override-pull: 
      wget https://content.runescape.com/downloads/ubuntu/runescape.gpg.key -O $SNAPCRAFT_PART_SRC/runescape.gpg.key
    build-packages:
      - wget
  
  rs3:
    plugin: dump
    source: rs3/
    stage-packages:
      - x11-utils
      - libgtk2.0-0
      - libsdl2-2.0-0
      - libpulse0
      - libasound2
      - libasound2-plugins
      - libglu1-mesa
      - gnupg
      - wget
      - p7zip-full
      - libopengl0
      - libegl1

  osrs:
    plugin: dump
    source: osrs
    stage-packages:
      - x11-utils
      - default-jre
      - libpulse0
      - wget
      - libasound2
      - libasound2-plugins
      - p7zip-full
      - libglu1-mesa
      - libgtk2.0-0
    build-packages:
      - ca-certificates
      - ca-certificates-java

  extras:
    plugin: dump
    source: extras/
    
environment:
  LANG: C.UTF-8

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm



apps:
  rs3:
    command: bin/rs3-launcher
    plugs:
      - desktop
      - desktop-legacy
      - network
      - audio-playback
      - x11
      - wayland
      - opengl
      - gsettings
      - pulseaudio
    environment:
      PULSE_LATENCY_MSEC: 150
      PULSE_PROP_OVERRIDE: application.name='RuneScape' application.icon_name='rs3.png' media.role='game'
      SDL_VIDEODRIVER: x11
      EGL_PLATFORM: x11
      SDL_VIDEO_X11_WMCLASS: RuneScape
      SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS: 0
    command-chain:
      - bin/setup-sandbox

  osrs:
    command: bin/osrs-launcher
    plugs:
      - desktop
      - desktop-legacy
      - network
      - audio-playback
      - x11
      - wayland
      - opengl
      - gsettings
      - pulseaudio
    environment:
      PULSE_PROP_OVERRIDE: application.name='Old School RuneScape' application.icon_name='osrs.png' media.role='game'
      ALSA_CONFIG_PATH: $SNAP/etc/asound.conf
    command-chain: 
      - bin/setup-sandbox

  reset:
    command: bin/reset-cache
