name: rslauncher
base: core18
title: RuneScape
version: git
summary: RuneScape, the free MMORPG by Jagex LTD
description: |
  Explore the fantasy world of Gielinor in the worlds most popular free to play MMORPG!
  This snap provides both Old School RuneScape and RuneScape 3!
  This is an unofficial package provided by Hmm.

type: app
grade: stable
confinement: strict
license: MIT
architectures:
  - build-on: amd64
    run-on: amd64

parts:
  rs3-gpg:
    plugin: dump
    source: .
    override-pull: 
      wget https://content.runescape.com/downloads/ubuntu/runescape.gpg.key -O $SNAPCRAFT_PART_SRC/runescape.gpg.key

  
  rs3:
    plugin: dump
    source: rs3/
    stage-packages:
      - libnotify-bin
      - x11-utils
      - libpango-1.0-0
      - libcairo2
      - libgdk-pixbuf2.0-0
      - libpangocairo-1.0-0
      - libgtk2.0-0
      - libsdl2-2.0-0
      - libpulse0
      - libglu1-mesa
      - dpkg
      - gnupg
      - wget
      - libasound2
      - libasound2-plugins


  osrs:
    plugin: dump
    source: osrs
    stage-packages:
      - libnotify-bin
      - x11-utils
      - default-jre
      - libpulse0
      - wget
      - libasound2
      - libasound2-plugins
    build-packages:
      - ca-certificates
      - ca-certificates-java

  
  utils:
    plugin: dump
    source: utils/

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm



apps:
  rs3:
    command: bin/rs3-launcher
    desktop: usr/share/applications/rs3.desktop
    plugs:
      - desktop
      - desktop-legacy
      - network
      - audio-playback
      - x11
      - wayland
      - opengl

    environment:
      SDL_AUDIODRIVER: alsa
      ALSA_CONFIG_PATH: $SNAP/etc/asound.conf
      PULSE_PROP_OVERRIDE: application.name='RuneScape' application.icon_name='rs3.png' media.role='game'
      SDL_VIDEO_X11_WMCLASS: RuneScape

  osrs:
    command: bin/osrs-launcher
    desktop: usr/share/applications/osrs.desktop
    plugs:
      - desktop
      - desktop-legacy
      - network
      - audio-playback
      - x11
      - wayland
      - opengl
    
    environment:
      _JAVA_OPTIONS: -Duser.home="$SNAP_USER_COMMON"
      PULSE_PROP_OVERRIDE: application.name='Old School RuneScape' application.icon_name='osrs.png' media.role='game'
      ALSA_CONFIG_PATH: $SNAP/etc/asound.conf

  reset:
    command: reset-cache


  sources:
    command: list-sources
